/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-menu.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

declare namespace UiElements {

  /**
   * Side navigation for Advanced REST Client.
   *
   * ### Styling
   * `<arc-menu>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-menu` | Mixin applied to the element | `{}`
   * `--arc-menu-bottom-actions` | Mixin applied to the bottom pane with additional actions. | `{}`
   * `--arc-menu-bottom-actions-button` | Mixin applied to the buttons in bottom action pane. | `{}`
   * `--arc-menu-bottom-actions-button-hover` | Mixin applied to the buttons in bottom action pane when hovering. | `{}`
   * `--arc-menu-tabs-color` | Color of the papaer tabs | ``
   * `--arc-menu-tabs-color-unselected` | Color of the papaer tabs when not selected | ``
   */
  class ArcMenu extends PolymerElement {

    /**
     * Currently selected menu tab
     */
    selected: number|null|undefined;
    _savedWarningOpened: boolean|null|undefined;

    /**
     * Changes information density of list items.
     * By default it uses material's peper item with two lines (72px heigth)
     * Possible values are:
     *
     * - `default` or empty - regular list view
     * - `comfortable` - enables MD single line list item vie (52px heigth)
     * - `compact` - enables list that has 40px heigth (touch recommended)
     */
    listType: string|null|undefined;

    /**
     * If set the history menu is rendered. This cames from application
     * settings and is different from `noHistory` which is intended to
     * temporaily remove the history from the view (for menu popup option)
     */
    historyEnabled: boolean|null|undefined;

    /**
     * When set it hiddes history from the view
     */
    hideHistory: boolean|null|undefined;

    /**
     * When set it hiddes saved list from the view
     */
    hideSaved: boolean|null|undefined;

    /**
     * When set it hiddes projects from the view
     */
    hideProjects: boolean|null|undefined;

    /**
     * When set it hiddes APIs list from the view
     */
    hideApis: boolean|null|undefined;

    /**
     * Renders popup menu buttons when this property is set.
     */
    allowPopup: boolean|null|undefined;

    /**
     * Adds draggable property to the request list item element.
     * The `dataTransfer` object has `arc/request-object` mime type with
     * serialized JSON with request model.
     */
    draggableEnabled: boolean|null|undefined;

    /**
     * A timeout after which the project item is opened when dragging a
     * request over.
     */
    dragOpenTimeout: number|null|undefined;
    _selectedChanged(selected: any): void;
    _navigateScreen(base: any): void;
    _openHistoryList(): void;
    _openSavedList(): void;
    _openApisList(): void;
    _exporeApis(): void;
    _refreshList(type: any): void;

    /**
     * Forces to refresh history list
     */
    refreshHistoryList(): void;

    /**
     * Forces to refresh saved list
     */
    refreshSavedList(): void;

    /**
     * Forces to refresh projects list
     */
    refreshProjectsList(): void;

    /**
     * Forces to refresh apis list
     */
    refreshApisList(): void;

    /**
     * Dispatches `popup-menu` custom event
     *
     * @param type Panel name
     */
    _popupMenu(type: String|null): void;

    /**
     * Requests to popup history menu.
     */
    popupHistory(): void;

    /**
     * Requests to popup saved menu.
     */
    popupSaved(): void;

    /**
     * Requests to popup projects menu.
     */
    popupProjects(): void;

    /**
     * Requests to popup apis menu.
     */
    popupApis(): void;
    _toggleSavedWarning(): void;
    _openSavedRemovalTicket(): void;

    /**
     * Computes condition value if history menu should be rendered
     *
     * @param selected Currently selected panel
     */
    _computeHistoryOpened(selected: Number|null, historyEnabled: Boolean|null, hideHistory: Boolean|null): Boolean|null;

    /**
     * Computes condition value if saved menu should be rendered
     *
     * @param selected Currently selected panel
     */
    _computeSavedOpened(selected: Number|null, hideSaved: Boolean|null): Boolean|null;

    /**
     * Computes condition value if projects menu should be rendered
     *
     * @param selected Currently selected panel
     */
    _computeProjectsOpened(selected: Number|null, hideProjects: Boolean|null): Boolean|null;

    /**
     * Computes condition value if saved apis should be rendered
     *
     * @param selected Currently selected panel
     */
    _computeApisOpened(selected: Number|null, hideApis: Boolean|null): Boolean|null;

    /**
     * Calls `notifyResize()` of the tabs to re-render selection.
     */
    _rerenderTabs(): void;

    /**
     * Selects first panel that is not hidden
     */
    _selectFirstAvailable(): void;

    /**
     * Calls `_selectFirstAvailable()` if `panelId` is current selection.
     */
    _updateSelectionIfNeeded(panelId: Number|null): void;

    /**
     * Updates selection when history panel is removed
     */
    _hideHistoryChanegd(val: Boolean|null): void;

    /**
     * Updates selection when saved panel is removed
     */
    _hideSavedChanegd(val: Boolean|null): void;

    /**
     * Updates selection when saved panel is removed
     */
    _hideProjectsChanegd(val: Boolean|null): void;

    /**
     * Updates selection when saved panel is removed
     */
    _hideApisChanegd(val: Boolean|null): void;

    /**
     * Updates selection when history is disabled/enabled
     */
    _historyEnabledChanegd(val: Boolean|null, old: Boolean|null): void;

    /**
     * Finds paper-tab element in event path.
     *
     * @param e Event with `path` or `composedPath()`
     */
    _findPaperTab(e: Event|null): Element|null|undefined;

    /**
     * Handler for `dragover` event on paper tabs.
     * Opens the tab if the dragged element can be dropped in corresponding menu.
     */
    _dragoverHandler(e: DragEvent|null): void;

    /**
     * Handler for `dragleave` event on project node.
     */
    _dragleaveHandler(e: DragEvent|null): void;

    /**
     * Cancels the timer set in the dragover event
     */
    _cancelDragTimeout(): void;
    _openMenuDragOver(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "arc-menu": UiElements.ArcMenu;
  }
}

export {};
