/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/HistoryMenu.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

import {HistoryListMixin} from '@advanced-rest-client/history-list-mixin/history-list-mixin.js';

import {RequestsListMixin} from '@advanced-rest-client/requests-list-mixin/requests-list-mixin.js';

import {AnypointMenuMixin} from '@anypoint-web-components/anypoint-menu-mixin/anypoint-menu-mixin.js';

export {HistoryMenuWrapper};

declare class HistoryMenuWrapper {
  render(): any;
}

export {HistoryMenu};

declare namespace UiElements {

  /**
   * A list of history requests in the ARC main menu.
   *
   * The element uses direct implementation of the PouchDB to make a query to the
   * datastore. It also listens to events fired by the `arc-model` elements to
   * update state of the history requests.
   *
   * ### Example
   * ```
   * <history-menu></history-menu>
   * ```
   *
   * ### Sizing the element
   *
   * The element uses `<iron-list>` to render the data in the view. The list is set
   * to be flex vertically. It means that the element has to be sized directly by the
   * hosting application or otherwise it size will be 0px.
   *
   * It can be done using flex layout and making the element to be `flex: 1`.
   *
   * ## Required dependencies
   *
   * The element works with `@advanced-rest-client/arc-models/request-model.js`
   * component. It should be included into the DOM.
   *
   * ### Styling
   * `<history-menu>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--history-menu-background-color` | Background color of the menu | `inherit`
   * `--history-menu-selected-post-method-color` | Font color of selected item POST method label | `#fff`
   * `--history-menu-focused-post-method-color` | Font color of focused item POST method label | `rgb(33, 150, 243)`
   * `--history-menu-selected-method-label-background-color` | Bg color of the POST method when focused | `#fff`
   * `--history-menu-selected-item-background-color` | Background color of the selected list item | `#FF9800`
   * `--history-menu-selected-item-color` | Color of the selected list item | `#fff`
   * `--history-menu-history-group-header-font-weigth` | Group header border color | `bold`
   * `--history-menu-history-group-header-border-color` | Group header border color | `#ddd`
   * `--history-menu-history-group-header-color` | Font color of the group header` | `rgba(0, 0, 0, 0.54)`
   * `--arc-menu-empty-info-color` | Color applied to the empty info section | ``
   * `--arc-menu-empty-info-title-color` | Color applied to the title in the empty info section | ``
   */
  class HistoryMenu extends
    RequestsListMixin(
    HistoryListMixin(
    Object)) {
    readonly _list: any;

    /**
     * Database ID of the selected item.
     */
    selectedItem: string|null|undefined;

    /**
     * Adds draggable property to the request list item element.
     * The `dataTransfer` object has `arc/request-object` mime type with
     * serialized JSON with request model.
     */
    draggableEnabled: boolean|null|undefined;

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;
    _unavailableTemplate(): any;
    _listTemplate(): any;
    render(): any;
    connectedCallback(): void;
    disconnectedCallback(): void;
    firstUpdated(): void;
    _addScrollEvent(): void;

    /**
     * Called every time the element changed it's scroll position. It will call the `makeQuery`
     * function when there's less than 120px left to scroll. (also it must be opened and must not
     * already querying).
     */
    _scrollHandler(): void;

    /**
     * Handler for the `click` event on the item.
     */
    _openHistory(e: ClickEvent|null): void;

    /**
     * Handler for the `dragstart` event added to the list item when `draggableEnabled`
     * is set to true.
     * This function sets request data on the `dataTransfer` object with `arc/request-object`
     * mime type. The request data is a serialized JSON with request model.
     */
    _dragStart(e: Event|null): void;
    _selectionChanged(e: any): void;
  }
}
